config/routes.rb
Rails.application.routes.draw do

  get 'dashboard/index'

  resources :tracks
  resources :styles
  resources :artists
  resources :favourites, only: [:create]

  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  get 'home/index'
  get 'home/favourites', to: 'home#user_tracks_favourites'

end

app/models/track.rb
class Track < ApplicationRecord
  searchkick

  belongs_to :artist
  belongs_to :style

  has_many :favourites

  def is_favourite_by_user?(user)
    self.favourites.any? { |f| f.user == user}
  end

  def search_data
    {
      name: name,
      style: style.name,
      artist: artist.name
    }
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track, only: [:show, :edit, :update, :destroy]
  before_action :check_permission

  # GET /tracks
  # GET /tracks.json
  def index
    @tracks = Track.all
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
  end

  # GET /tracks/new
  def new
    @track = Track.new
  end

  # GET /tracks/1/edit
  def edit
  end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = Track.new(track_params)

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: 'Track was successfully created.' }
        format.json { render :show, status: :created, location: @track }
      else
        format.html { render :new }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracks/1
  # PATCH/PUT /tracks/1.json
  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
        format.json { render :show, status: :ok, location: @track }
      else
        format.html { render :edit }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    @track.destroy
    respond_to do |format|
      format.html { redirect_to tracks_url, notice: 'Track was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track
      @track = Track.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def track_params
      params.require(:track).permit(:name, :artist_id, :style_id)
    end
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/tracks/_form.html.erb
<%= form_with(model: track, local: true) do |form| %>
  <% if track.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
      <% track.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field">
    <%= form.text_field :name, id: :track_name, required: true %>
    <%= form.label :name %>
  </div>

  <div class="input-field">
    <%= form.select :artist_id, Artist.all.collect {|p| [ p.name, p.id ] }, { include_blank: true }, required: true %>
    <%= form.label :artist %>
  </div>

  <div class="input-field">
    <%= form.select :style_id, Style.all.collect {|p| [ p.name, p.id ] }, { include_blank: true }, required: true %>
    <%= form.label :style %>
  </div>

  <div class="input-field">
    <%= form.submit class: 'btn' %>
  </div>
<% end %>

app/views/tracks/edit.html.erb
<%= render 'shared/aside' %>

<%= render 'shared/header' %>

<div class="container">

    <div class="row top-30">
      <div class="col s12">
        <h5>Editing Track</h5>
      </div>
    </div>

    <div class="row">
      <div class="col s12">
        <%= render 'form', track: @track %>
      </div>
    </div>
    
    <div class="row top-20">
      <div class="col s12">
        <%= link_to 'Show', @track, class: 'btn' %>
        <%= link_to 'Back', tracks_path, class: 'btn' %>
    </div>
  </div>

</div>

app/views/tracks/index.html.erb
<%= render 'shared/aside' %>

<%= render 'shared/header' %>

<div class="container">

  <div class="row top-30">
    <div class="col s8">
      <h5>Tracks</h5>
    </div>
    <div class="col s4 right-align">
      <%= link_to 'New Track', new_track_path, class: 'btn' %>
    </div>
  </div>

  <div class="row">
    <div class="col s12">
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Artist</th>
            <th>Style</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @tracks.each do |track| %>
            <tr>
              <td><%= track.name %></td>
              <td><%= track.artist.name %></td>
              <td><%= track.style.name %></td>
              <td>
                <%= link_to 'Show', track, class: 'btn' %>
                <%= link_to 'Edit', edit_track_path(track), class: 'btn' %>
                <%= link_to 'Destroy', track, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

</div>

app/views/tracks/new.html.erb
<%= render 'shared/aside' %>

<%= render 'shared/header' %>

<div class="container">

  <div class="row top-30">
    <div class="col s12">
      <h5>New Track</h5>
    </div>
  </div>

  <div class="row">
    <div class="col s12">
      <%= render 'form', track: @track %>
    </div>
  </div>

</div>

app/views/tracks/show.html.erb
<%= render 'shared/aside' %>

<%= render 'shared/header' %>

<div class="container">

  <div class="row top-30">
    <div class="col s12">
      <table>
        <thead>
          <tr>
              <th>Name</th>
              <th>Artist</th>
              <th>Style</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @track.name %></td>
            <td><%= @track.artist.name %></td>
            <td><%= @track.style.name %></td>
          </tr>
        </tbody>
      </table>
      </div>
  </div>

  <div class="row">
    <div class="col s12">
    <%= link_to 'Edit', edit_track_path(@track), class: 'btn' %>
    <%= link_to 'List', tracks_path, class: 'btn' %>
  </div>

</div>