config/routes.rb
Rails.application.routes.draw do

  get 'dashboard/index'

  resources :tracks
  resources :styles
  resources :artists
  resources :favourites, only: [:create]

  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  get 'home/index'
  get 'home/favourites', to: 'home#user_tracks_favourites'

end

app/models/artist.rb
class Artist < ApplicationRecord
  include Favouritable

  has_many :tracks
  has_many :favourites, through: :tracks

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]
  before_action :check_permission

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name)
    end

end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<%= form_with(model: artist, local: true) do |form| %>
  <% if artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field">
    <%= form.text_field :name, id: :artist_name, required: true %>
    <%= form.label :name %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn' %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<%= render 'shared/aside' %>

<h1>Editing Artist</h1>

<%= render 'form', artist: @artist %>

app/views/artists/index.html.erb
<%= render 'shared/aside' %>

<%= render 'shared/header' %>

<div class="container">

  <div class="row top-30">
    <div class="col s8">
      <h5>Artists</h5>
    </div>
    <div class="col s4 right-align">
      <%= link_to 'New Artist', new_artist_path, class: 'btn' %>
    </div>
  </div>

  <div class="row">
    <div class="col s12">
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @artists.each do |artist| %>
            <tr>
              <td><%= artist.name %></td>
              <td><%= link_to 'Show', artist, class: 'btn' %></td>
              <td><%= link_to 'Edit', edit_artist_path(artist), class: 'btn' %></td>
              <td><%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

</div>

app/views/artists/new.html.erb
<%= render 'shared/aside' %>

<%= render 'shared/header' %>

<div class="container">

  <div class="row top-30">
    <div class="col s12">
      <h5>New Artist</h5>
    </div>
  </div>

  <div class="row top-30">
    <div class="col s12">
      <%= render 'form', artist: @artist %>
    </div>
  </div>

</div>

app/views/artists/show.html.erb
<%= render 'shared/aside' %>

<%= render 'shared/header' %>

<div class="container">

  <div class="row top-30">
    <div class="col s12">
      <table>
        <thead>
          <tr>
              <th>Name</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @artist.name %></td>
          </tr>
        </tbody>
      </table>
      </div>
  </div>

  <div class="row">
    <div class="col s12">
      <%= link_to 'Edit', edit_artist_path(@artist), class: 'btn' %>
      <%= link_to 'List', artists_path, class: 'btn' %>
    </div>
  </div>

</div>