config/routes.rb
Rails.application.routes.draw do

  get 'dashboard/index'

  resources :tracks
  resources :styles
  resources :artists
  resources :favourites, only: [:create]

  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  get 'home/index'
  get 'home/favourites', to: 'home#user_tracks_favourites'

end

app/views/shared/_aside.html.erb
<aside id="slide-out" class="side-nav">

  <ul>

    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'Profile', edit_user_registration_path %></li>
    <li><%= link_to('Log out', destroy_user_session_path, method: 'delete') %></li>

    <% if current_user.admin? %>

    <li><div class="divider"></div></li>
    <li><%= link_to 'Dashboard', dashboard_index_path %></li>

    <li><div class="divider"></div></li>
    <li><a class="subheader">Style</a></li>
    <li><%= link_to 'New', new_style_path %></li>
    <li><%= link_to 'List', styles_path %></li>

    <li><div class="divider"></div></li>
    <li><a class="subheader">Artists</a></li>
    <li><%= link_to 'New', new_artist_path %></li>
    <li><%= link_to 'List', artists_path %></li>

    <li><div class="divider"></div></li>
    <li><a class="subheader">Tracks</a></li>
    <li><%= link_to 'New', new_track_path %></li>
    <li><%= link_to 'List', tracks_path %></li>

    <% end %>

  </ul>

</aside>

app/views/shared/_header.html.erb
<header class="navbar">
  <nav class="teal darken-1">
    <div class="nav-wrapper container">
      <%= link_to 'Favourite Music', root_path, class: 'brand-logo' %>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="#" data-activates="slide-out" class="aside-menu-collapse">MENU</a></li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_item_menu.html.erb
<li><%= link_to locals[:name], locals[:path] %></li>

app/views/shared/_notifications.html.erb
<%= javascript_tag "Materialize.toast('#{notice}', 4000)" if notice %>

<%= javascript_tag "Materialize.toast('#{alert}', 4000)" if alert %>