config/routes.rb
Rails.application.routes.draw do

  get 'dashboard/index'

  resources :tracks
  resources :styles
  resources :artists
  resources :favourites, only: [:create]

  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  get 'home/index'
  get 'home/favourites', to: 'home#user_tracks_favourites'

end

app/models/style.rb
class Style < ApplicationRecord
  include Favouritable

  has_many :tracks
  has_many :favourites, through: :tracks

end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  before_action :set_style, only: [:show, :edit, :update, :destroy]
  before_action :check_permission

  # GET /styles
  # GET /styles.json
  def index
    @styles = Style.all
  end

  # GET /styles/1
  # GET /styles/1.json
  def show
  end

  # GET /styles/new
  def new
    @style = Style.new
  end

  # GET /styles/1/edit
  def edit
  end

  # POST /styles
  # POST /styles.json
  def create
    @style = Style.new(style_params)

    respond_to do |format|
      if @style.save
        format.html { redirect_to @style, notice: 'Style was successfully created.' }
        format.json { render :show, status: :created, location: @style }
      else
        format.html { render :new }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /styles/1
  # PATCH/PUT /styles/1.json
  def update
    respond_to do |format|
      if @style.update(style_params)
        format.html { redirect_to @style, notice: 'Style was successfully updated.' }
        format.json { render :show, status: :ok, location: @style }
      else
        format.html { render :edit }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /styles/1
  # DELETE /styles/1.json
  def destroy
    @style.destroy
    respond_to do |format|
      format.html { redirect_to styles_url, notice: 'Style was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_style
      @style = Style.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def style_params
      params.require(:style).permit(:name)
    end
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/views/styles/_form.html.erb
<%= form_with(model: style, local: true) do |form| %>
  <% if style.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(style.errors.count, "error") %> prohibited this style from being saved:</h2>

      <ul>
      <% style.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field">
    <%= form.text_field :name, id: :style_name, required: true %>
    <%= form.label :name %>
  </div>

  <div class="input-field">
    <%= form.submit class: 'btn' %>
  </div>
<% end %>

app/views/styles/edit.html.erb
<%= render 'shared/aside' %>

<%= render 'shared/header' %>

<div class="container">

    <div class="row top-30">
      <div class="col s12">
        <h5>Editing Style</h5>
      </div>
    </div>

    <div class="row">
      <div class="col s12">
        <%= render 'form', style: @style %>
      </div>
    </div>
    
    <div class="row top-20">
      <div class="col s12">
        <%= link_to 'Show', @style, class: 'btn' %>
        <%= link_to 'Back', styles_path, class: 'btn' %>
    </div>
  </div>

</div>

app/views/styles/index.html.erb
<%= render 'shared/aside' %>

<%= render 'shared/header' %>

<div class="container">

  <div class="row top-30">
    <div class="col s8">
      <h5>Styles</h5>
    </div>
    <div class="col s4 right-align">
      <%= link_to 'New Style', new_style_path, class: 'btn' %>
    </div>
  </div>

  <div class="row">
    <div class="col s12">
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @styles.each do |style| %>
            <tr>
              <td><%= style.name %></td>
              <td><%= link_to 'Show', style, class: 'btn' %></td>
              <td><%= link_to 'Edit', edit_style_path(style), class: 'btn' %></td>
              <td><%= link_to 'Destroy', style, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

</div>

app/views/styles/new.html.erb
<%= render 'shared/aside' %>

<%= render 'shared/header' %>

<div class="container">

  <div class="row top-30">
    <div class="col s12">
      <h5>New Style</h5>
    </div>
  </div>

  <div class="row">
    <div class="col s12">
      <%= render 'form', style: @style %>
    </div>
  </div>


</div>

app/views/styles/show.html.erb
<%= render 'shared/aside' %>

<%= render 'shared/header' %>

<div class="container">

  <div class="row top-30">
    <div class="col s12">
      <table>
        <thead>
          <tr>
              <th>Name</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @style.name %></td>
          </tr>
        </tbody>
      </table>
      </div>
  </div>

  <div class="row">
    <div class="col s12">
    <%= link_to 'Edit', edit_style_path(@style), class: 'btn' %>
    <%= link_to 'List', styles_path, class: 'btn' %>
  </div>

</div>